export const DataFactoryDT = [
  {
    type: 2,
    ten: 'Uông Bí',
    fullName: 'Công ty NĐ Uông Bí',
    congsuat: 300+ 330,
    diachi: 'Khu 6, phường Quang Trung, thành phố Uông Bí, tỉnh Quảng Ninh',
    tomays: [
      {ten: 'S7', congsuat: 300, pmin: 250, pmax: 290},
      {ten: 'S8', congsuat: 330, pmin: 231, pmax: 330},
    ],
    pmin: 250 + 231,
    pmax: 290 + 330,
    khothan: 'Có 3 kho than, sức chứa tối đa: 95.000 tấn',
  },
  {
    type: 2,
    ten: 'Nghi Sơn',
    fullName: 'Công ty NĐ Nghi Sơn',
    congsuat: 300 + 300,
    diachi: 'Km 11, đường 513, xã Hải Hà, thị xã Nghi Sơn, tỉnh Thanh Hóa',
    tomays: [
      {ten: 'S1', congsuat: 300, pmin: 180, pmax: 300},
      {ten: 'S1', congsuat: 300, pmin: 180, pmax: 300},
    ],
    pmin: 180 + 180,
    pmax: 600,
    khothan: 'Có 3 kho than, sức chứa tối đa: 95.000 tấn',
  },
  {
    type: 2,
    ten: 'D.Hải',
    fullName: 'Công ty NĐ Duyên Hải ',
    congsuat: 622.5 * 4 + 688,
    diachi: 'Ấp Mù U, xã Dân Thành, thị xã Duyên Hải, tỉnh Trà Vinh',
    tomays: [
      {ten: 'S1DH1', congsuat: 622.5, pmin: 435.75, pmax: 622.5},
      {ten: 'S2DH2', congsuat: 622.5, pmin: 435.75, pmax: 622.5},
      {ten: 'S1DH3', congsuat: 622.5, pmin: 218, pmax: 622.5},
      {ten: 'S2DH3', congsuat: 622.5, pmin: 218, pmax: 622.5},
      {ten: 'S3DH3MR', congsuat: 688, pmin: 218, pmax: 688},
    ],
    pmin: 435.75 * 2 + 218 * 3,
    pmax: 622.5 * 4 + 688,
    khothan: 'Có 3 kho than, sức chứa tối đa: 95.000 tấn',
  },
  {
    type: 2,
    ten: 'Q.Ninh',
    fullName: 'Công ty CPNĐ Quảng Ninh',
    congsuat: 300 * 4,
    diachi: 'Phường Hà Khánh, TP.Hạ Long, Quảng Ninh',
    tomays: [
      {ten: 'S1', congsuat: 300, pmin: 230, pmax: 300},
      {ten: 'S2', congsuat: 300, pmin: 230, pmax: 300},
      {ten: 'S3', congsuat: 300, pmin: 230, pmax: 300},
      {ten: 'S4', congsuat: 300, pmin: 230, pmax: 300},
    ],
    pmin: 230 * 4,
    pmax: 300 * 4,
    khothan: 'Có 3 kho than, sức chứa tối đa: 95.000 tấn',
  },
];

export const DataFactoryTD = [
  {
    type: 1,
    ten: 'Bản Vẽ',
    fullName: 'Công ty TĐ Bản Vẽ',
    congsuat: 320,
    diachi: 'Đường Lê Nin, phường Hưng Phúc, thành Phố Vinh, tỉnh Nghệ An',
    tomays: [
      {
        ten: 'Bản Vẽ',
        diachi: 'Yên Na, Tương Dương, Nghệ An',
        tomay: 2,
        congsuat: 320,
        pmin: 110,
        pmax: 160,
      },
    ],
    pmin: 110,
    pmax: 160,
  },
  {
    type: 1,
    ten: 'Sông Tranh',
    fullName: 'Công ty TĐ Sông Tranh',
    congsuat: 190,
    diachi: '04 Quy Mỹ, Phường Hòa Cường Nam, quận Hải Châu, Thành phố Đà Nẵng',
    tomays: [
      {
        ten: 'Sông Tranh',
        diachi: 'Trà Đốc, Bắc Trà My, Quảng Nam',
        tomay: 2,
        congsuat: 190,
        pmin: 40,
        pmax: 95,
      },
    ],
    pmin: 40,
    pmax: 95,
  },
  {
    type: 1,
    ten: 'Đại Ninh',
    fullName: 'Công ty TĐ Đại Ninh',
    congsuat: 300,
    diachi: 'Xã Ninh Gia, huyện Đức Trọng, tỉnh Lâm Đồng',
    tomays: [
      {
        ten: 'Đại Ninh',
        diachi: 'Phan Lâm, Bắc Bình, Bình Thuận',
        tomay: 2,
        congsuat: 300,
        pmin: 10,
        pmax: 150,
      },
    ],
    pmin: 10,
    pmax: 150,
  },
  {
    type: 1,
    ten: 'Đồng Nai',
    fullName: 'Công ty TĐ Đồng Nai',
    congsuat: 180 + 340,
    diachi: '254 Trần Phú, TP Bảo Lộc, Lâm Đồng',
    tomays: [
      {
        ten: 'Đồng Nai 3',
        diachi:
          'Tại xã Đắk Som, Đắk Glong, Đăk Nông và xã Lộc Lâm, Bảo Lâm, Lâm Đồng',
        tomay: 2,
        congsuat: 180,
        pmin: 60,
        pmax: 90,
      },
      {
        ten: 'Đồng Nai 4',
        diachi:
          'Tại xã Đắk Som, Đắk Glong, Đăk Nông và xã Lộc Lâm, Bảo Lâm, Lâm Đồng',
        tomay: 2,
        congsuat: 340,
        pmin: 60,
        pmax: 170,
      },
    ],
    pmin: 60 + 60,
    pmax: 90 + 170,
  },
  {
    type: 1,
    ten: 'Đa Nhim - Hàm Thuận - Đa Mi',
    fullName: 'Công ty CPTĐ Đa Nhim - Hàm Thuận - Đa Mi',
    congsuat: 160 + 80 + 300 + 175,
    diachi: '80A Trần Phú, phường Lộc Sơn, TP. Bảo Lộc, tỉnh Lâm Ðồng',
    tomays: [
      {
        ten: 'Đa Nhim',
        diachi: 'Thị trấn D`Ran, Đơn Dương, Lâm Đồng',
        tomay: 4,
        congsuat: 160,
        pmin: 5,
        pmax: 40,
      },
      {
        ten: 'Đa Nhim MR',
        diachi: 'Xã Lâm Sơn, Ninh Sơn, Ninh Thuận',
        tomay: 1,
        congsuat: 80,
        pmin: 5,
        pmax: 80,
      },
      {
        ten: 'Hàm Thuận',
        diachi: 'Đông Tiến, Hàm Thuận Bắc, Bình Thuận',
        tomay: 2,
        congsuat: 300,
        pmin: 60,
        pmax: 150,
      },
      {
        ten: 'Đa Mi',
        diachi: 'La Ngâu, Tánh Linh, Bình Thuận',
        tomay: 2,
        congsuat: 175,
        pmin: 50,
        pmax: 87.5,
      },
      {
        ten: 'NMĐ mặt trời Đa Mi',
        diachi: 'La Ngâu, Tánh Linh, Bình Thuận',
        tomay: 0,
        congsuat: 0,
        pmin: 0,
        pmax: 0,
      },
    ],
    pmin: 5 + 5 + 60 + 50 + 0,
    pmax: 40 + 80 + 150 + 87.5 + 0,
  },
  {
    type: 1,
    ten: 'CPPT DL Việt Nam',
    fullName: 'Công ty CPPT Điện lực Việt Nam',
    congsuat: 320,
    diachi:
      'Tầng 2 - CT2 - Số 286 Nguyễn Xiển, xã Tân Triều, huyện Thanh Trì, Hà Nội',
    tomays: [
      {
        ten: 'Khe Bố',
        diachi: 'Tam Quang, Tương Dương, Nghệ An',
        tomay: 2,
        congsuat: 100,
        pmin: 13.2,
        pmax: 50,
      },
      {
        ten: 'Bắc Bình',
        diachi: 'Bắc Bình, Bình Thuận',
        tomay: 2,
        congsuat: 33,
        pmin: 8,
        pmax: 15,
      },
    ],
    pmin: 13.2 + 8,
    pmax: 50 + 15,
  },
];
